# -*- coding: utf-8 -*-
"""PTDLUD_07_VN#5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13rGVrtVcH61ZDVMkV73CmV5Gq_toJHnL
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statistics as st
df = pd.read_csv('Mall_Customers.csv', encoding = 'utf-8-sig')
df

df.info()
# Ý nghĩa thuộc tính của tập dữ liệu và danh sách các cột
#CustomerID: ID duy nhất được chỉ định cho khách hàng
#Gender: Giới tính của khách hàng
#Age: Tuổi của khách hàng
#Annual Income (k$): Thu nhập hàng năm của người giám hộ
#Spending Score (1-100): Điểm do trung tâm mua sắm chỉ định dựa trên hành vi của khách hàng và bản chất chi tiêu

df.describe()
# Tại thuộc tính Age, ta thấy được số tuổi của khách hàng trung bình mean là 38.850000, số tuổi lớn nhất và nhỏ nhất lần lượt là 70.000000 và 18.000000.
#=> Có thể thấy đối tượng của Mall là khách hàng đã trưởng thành tự chủ được tài chính hoặc ít nhất có trách nhiệm đối với hành vi của mình.
# Tại thuộc tính Annual Income, ta thấy được thu nhập trung bình là 60.560000 k$, số thu nhập lớn nhất và cao nhất lần lượt là 137.000000k$ và 15.000000k$.
#=> Có thể thấy thu nhập của khách hàng là khác nhau, việc biết được thu nhập của khách hàng cũng là một trong yếu tố quan trọng đến kinh, biết được khách hàng của mình là ai.
#Để có thể kinh doanh các sản phẩm phù hợp với khách hàng theo túi tiền của họ.
# Tại thuộc tính Spending Score, ta thấy điểm trung bình là 50.200000, điểm cao nhất và thấp nhất lần lượt là 99.000000 và 1.000000.
#=> Có thể khách hàng của Mall này, nhìn chung có mức điểm khá ổn định,nhưng độ chênh lệch của điểm cao nhất và thấp nhất là rất lớn.
#Điều này có thể xảy ra từ các lý do như khách hàng không hài lòng sản phẩm dịch bên Mall. Hay chế độ chăm sóc khách hàng không được đồng đều.
#Bên thì quan tâm chăm sóc, bên thì bỏ bê làm chêch lệch điểm khách hàng như vậy.

df.isnull().sum().sort_values(ascending=False)
# Tỷ lệ null của tất cả các cột là 0%

#vì tất cả các cột đều không chứa bất cứ giá trị NULL nào nên ta không cần xử lý bỏ NULL.
plt.hist(df['Age'])
plt.xlabel("Age")
plt.ylabel("Count")
print("Mean của Age: ",st.mean(df['Age']))
print("Median của Age: ",st.median(df['Age']))
print("Mode của Age: ",st.mode(df['Age']))
#với mode = 32 < median = 36 < mean = 38.85, biểu đồ này lệch về phía bên phải.
#dựa vào biểu đồ, ta thấy lượng khách hàng chính của Mall này có độ tuổi rơi vào khoảng 20 đến 40 tuổi. Độ tuổi trung bình của khách hàng là 38.85. 
#Khách hàng có tuổi là 32 chiếm số lượng lớn nhất.

plt.boxplot(df['Age'])
#biểu đồ boxplot dưới đây sẽ cho ta thấy rõ hơn ràng biểu đồ phân bố về độ tuổi của khách hàng lệch về phía bên phải.
#dữ liệu Age này không tồn tại outlier

plt.hist(df['Annual Income (k$)'])
plt.xlabel("Annual Income (k$)")
plt.ylabel("Count")
print("Mean của Annual Income: ",st.mean(df['Annual Income (k$)']))
print("Median của Annual Income: ",st.median(df['Annual Income (k$)']))
#với mean = 60.56 < median = 61.5, đồng thời khoảng chênh lệch giữa mean và median là không lớn, nên ta kết luận biểu đồ hơi lệch về phía bên trái.
#Mức thu nhập trung bình của khách hàng của Mall này là 60.56 nghìn$.

plt.boxplot(df['Annual Income (k$)'])
#biểu đồ boxplot dưới đây sẽ củng cố rõ hơn rằng phân bố về thu nhập của khách hàng là biểu đồ lệch trái.
#dữ liệu có tồn tại outlier với thu nhập rơi vào khoảng gần 140 nghìn$. Nhưng theo em outlier này chỉ chênh lệch ít so với max của khoảng 75% 
#nhưng đồng thời, đây là dữ liệu về thu nhập của khách hàng, nên chuyện có khách hàng có thu nhập cao hơn một chút so với phần lớn khách hàng
#là điều bình thường, nên em nghĩ outlier này không cần xử lý.

plt.hist(df['Spending Score (1-100)'])
plt.xlabel("Spending Score (1-100)")
plt.ylabel("Count")
print("Mean của Spending Score: ",st.mean(df['Spending Score (1-100)']))
print("Median của Spending Score: ",st.median(df['Spending Score (1-100)']))
print("Mode của Spending Score: ",st.mode(df['Spending Score (1-100)']))
#với mode = 43 < median = 50 < mean = 50.2, ta có thể kết luận biểu đồ phân phối điểm chi tiêu của khách hàng lệch về phía bên phải.
#lượng điểm chi tiêu trung bình của khách hàng là 50.2 điểm, trong đó khách hàng có lượng điểm chi tiêu là 42 là có số lượng nhiều nhất.

plt.boxplot(df['Spending Score (1-100)'])
#biểu đồ boxplot dưới đây sẽ củng cố thêm cho việc rằng biểu đồ phân phối điểm chi tiêu của khách hàng lệch về bên phải.
#dữ liệu về lượng điểm chi tiêu của khách hàng không tồn tại outlier.

# #Mối tương quan của giới tính với độ tuổi
plt.scatter(df["Gender"], df["Age"], )
plt.xlabel("Gender")
plt.ylabel("Age")
plt.show()

#Mối tương quan của giới tính với thu nhập hằng năm
plt.scatter(df["Gender"], df["Annual Income (k$)"])
plt.xlabel("Gender")
plt.ylabel("Annual Income (k$)")
plt.show()

# #Mối tương quan của giới tính với điểm chi tiêu
plt.scatter(df["Gender"], df["Spending Score (1-100)"])
plt.xlabel("Gender")
plt.ylabel("Spending Score (1-100)")
plt.show()
"""
Ta thấy cột giới tính với các cột thuộc tính khác đều không có sự tương quan 
"""

#Mối tương quan của độ tuổi đến thu nhập hằng năm
plt.scatter(df["Age"], df["Annual Income (k$)"])
plt.xlabel("Age")
plt.ylabel("Annual Income (k$)")
plt.show()

#Mối tương quan của độ tuổi đến điểm chi tiêu
plt.scatter(df["Age"], df["Spending Score (1-100)"])
plt.xlabel("Age")
plt.ylabel("Spending Score (1-100)")
plt.show()
"""
Ta thấy cột độ tuổi với mức thu nhập hằng năm của họ phân bố lộn xộn nên giữa chúng
không có sự tương quan 
Ta thấy cột độ tuổi với điểm số điểm chi tiêu của họ phân bố lộn xộn nên giữa chúng
không có sự tương quan 
"""

#Mối tương quan của thu nhập hằng năm đến điểm chi tiêu
plt.scatter(df["Annual Income (k$)"], df["Spending Score (1-100)"])
plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.show()
"""
Ta thấy cột tổng thu nhập hằng năm với điểm số điểm chi tiêu của họ phân bố lộn xộn nên giữa chúng
không có sự tương quan 
"""

# Ta sử dụng df.duplicated() để tìm ra dòng bị trùng
# Dùng print(df[df.duplicated()]) để hiển thị các dòng trùng
# Theo kết quả của câu lệnh ở dưới, ta thấy số dòng trung là 0 
print(df[df.duplicated()])

# Ta phân chia dữ liệu theo nhóm độ tuổi lần lượt là: 1-20, 21-40, 41-60, 61-80, 81-100
df1 = df[df['Age'].between(1, 20, inclusive=False)]

df2 = df[df['Age'].between(21, 40, inclusive=False)]

df3 = df[df['Age'].between(41, 60, inclusive=False)]

df4 = df[df['Age'].between(61, 80, inclusive=False)]

df5 = df[df['Age'].between(81, 100, inclusive=False)]

age = ['1-20','21-40','41-60','61-80','81-100']
quantity = [df1['Age'].count(),df2['Age'].count(),df3['Age'].count(),df4['Age'].count(),df5['Age'].count()]
plt.bar(age,quantity)
#plt.title('Age')
plt.xlabel('Age')
plt.ylabel('Quantity')
plt.show()
# Theo biểu đồ,ta có thể thấy khách hàng chủ lực của trung tâm thương mại là: nhóm 21-40 tuổi